### ISSUE TITLE
Updated APNs provider API deadline - Apple end support @ 31 March 2021

### ISSUE THREAD

**Issue by macciomauro** [codedge-llc/pigeon#181]
https://developer.apple.com/news/?id=c88acm2b#:~:text=To%20give%20you%20additional%20time,binary%20protocol%20after%20this%20date

As said in the linked news, "APNs will no longer support the legacy binary protocol after this date".

Will this create problems to the Pidgeon APN actual version or worse make it stop working at all? 
The FCM version can be used for iOS too, there can be the possibility that it will be affected too?

thanks a lot for this useful project

**Comment by hpopp** [comment]
Pigeon has been using the new http/2 protocol since practically the beginning 😄

I'll keep an eye on this for FCM. I don't personally know which protocol they're using for iOS dispatch, but I'm inclined to think they've already upgraded (pigeon connects to FCM over http/2 already).

Thanks for the heads up!
