### ISSUE TITLE
APNS pushes flaky

### ISSUE THREAD

**Issue by asgoel** [codedge-llc/pigeon#60]
I'm discovering that i'm having flaky success using the push worker to deliver messages. The `Pigeon.APNS.push` method returns `:ok`, but my callback never gets fired. What's the easiest way to diagnose what is happening? Could  the HTTP/2 connection be timing out?

**Comment by hpopp** [comment]
It very well could be, I need to add better logging options to kadabra. How long has the connection been running and what kind of volume of pushes are you sending?

**Comment by asgoel** [comment]
Usually around a day or so. I've just been testing one off pushes at a time
which is how I noticed.

**Comment by asgoel** [comment]
Shouldn't the heartbeat ping pick up if the connection is dropped?

**Comment by hpopp** [comment]
It should, I've explicitly fixed that issue in the past. Just out of curiosity, are you using the most recent release of kadabra?

**Comment by asgoel** [comment]
Yep, I thiunk so. Pigeon 0.10.3 and Kadabra 0.1.5

**Comment by asgoel** [comment]
Confirmed that this is an issue with Kadabra. The APNS worker is making the request, but never receiving the response from Kadabra. This happens after any number of Pings. any way to test?

**Comment by asgoel** [comment]
Did some more digging. At some point the socket is getting closed, because when I try an `ssl.send` it comes back with an `{:error, :closed}` response. Strangely enough, I don't see the GOAWAY Logger.error message, does that mean the socket was just raw closed?

**Comment by asgoel** [comment]
Confirmed that this only happens on my EC2 instance and not on my local machine. When it tries to send a ping it immediately receives an `ssl_closed` response on my EC2 instance. Any ideas why this could be happening?

**Comment by hpopp** [comment]
I have some ideas, but I'll need to test. I'll check as soon as I get a chance.

**Comment by asgoel** [comment]
Figured it out (I think). AWS NATs by default will close connections after 5 minutes of inactivity. Given that the ping period on the APNS worker is 10 minutes, the socket would get closed by AWS well before that. It would be great if the ping period could be configurable, to avoid this issue. I see some new PRs up so I'll wait for those to be merged before submitting something to make it configurable.

Feel free to keep open if you think there's another way to fix this.

**Comment by asgoel** [comment]
Closing this, as it was an AWS issue and you added configurable ping periods

**Comment by pgrunwald** [comment]
Hi @hpopp @asgoel, very glad I found this issue, we were experiencing similar behavior in Azure. I believe that Azure has something like a 4-minute limit for inactive connections, so it would make sense that the 10 minute ping interval would cause these connections to be closed by the cloud provider. I am trialling `ping_period: 60_000` to see if this resolves the issue.

This issue was quite difficult to diagnose, since, like @asgoel, I only noticed that callbacks weren't getting fired. There was no other feedback pointing me towards the potential issue other than that push notifications were only working intermittently with APNs.

If my problem is solved by changing `ping_period`, I think that we should either add a note about this to the docs, or set the default `ping_period` to something that won't get closed by the major cloud providers, or have some sort of error returned when the connection has been closed due to this.

I'm happy to have a go at whatever method is most appropriate for the library.

Thanks!

**Comment by hpopp** [comment]
Let's add a note to the docs for now. I'm tempted to reduce the default to 1-2 minutes, but I can't recall my reasoning for setting it at 10. It may no longer be relevant.
